dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

# deploy:
#   skip_cleanup: true
#   target-branch: master # Commit to master instead of gh-pages
#   github-token: $GITHUB_TOKEN
#   keep-history: true # By default, Travis uses push --force and wipes out commit history
#   verbose: true
#   on:
#     branch: master

script:
- ng build --prod --base-href docs

after_success:
  - ./push.sh

# - git commit -am "Deploy to GitHub pages"
# - git status
# - git branch tmp
# - git status
# - git checkout master
# - git status
# - git merge tmp
# - git status
# - git stash
# - git checkout master
# - git stash pop
# - git add .
# - git commit -am "Deploy to GitHub pages"
# - git push